version: '3.8'
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../ssl/certbot/conf:/etc/letsencrypt
      - ../ssl/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot -d ${DOMAIN_NAME} --email admin@selendra.org --agree-tos --no-eff-email --force-renewal
